"""Normalized trigger event schema emitted by entry and exit signal generators."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
import math
import time
from typing import Any, Dict, Optional


class TriggerAction(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    NEUTRAL = "NEUTRAL"


class TriggerSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass(frozen=True)
class TriggerEvent:
    """Actionable event generated by an entry/exit trigger before passing guards."""

    action: TriggerAction
    side: TriggerSide
    source: str
    symbol: str
    price: float
    strength: float
    ts: float = field(default_factory=time.time)
    velocity: Optional[float] = None
    confidence: Optional[float] = None
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def is_executable(self) -> bool:
        """Return True if this event requests an actual order (BUY or SELL)."""
        return (
            self.side in (TriggerSide.BUY, TriggerSide.SELL)
            and math.isfinite(self.price)
            and self.price > 0
            and self.action in (TriggerAction.ENTRY, TriggerAction.EXIT)
        )
